name: "test deployment"

on:
  workflow_dispatch: # manual trigger
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  terraform:
    name: "test terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: terraform init
        id: init
        run: |
          rm -rf .terraform
          terraform init

      - name: terraform apply
        id: apply
        run: terraform apply

      - name: terraform destroy
        id: destroy
        run: terraform destroy