name: "test deployment"

on:
  workflow_dispatch: # manual trigger

permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout

defaults:
  run:
    shell: bash

jobs:
  terraform:
    name: "test terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform Init
        id: init
        run: |
          rm -rf .terraform
          terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy